.\" To report problems with this software, visit http://bugzilla.ximian.com
.TH "rcd.config" "5" "1.0" "Ximian, Inc. 2002" "RCD Configuration File"
.SH "NAME"
rcd.conf \- Red Carpet Daemon (rcd) configuration file.
.SH "DESCRIPTION"
The Red Carpet Daemon, rcd, uses a system\-wide configuration file for setting various options related to its operation. You may edit the configuration file directly, or set options using one of the rcd clients. The most obvious mechanism for doing so is the \fIrc set\fR command. See the rc man page for more information.
.SH "CONFIGURATION FILE FORMAT"
.LP 
The configuration file is in the GNOME config file format, similar to Windows .ini files.  Entries are grouped into sections.  A section begins with the line:
.LP 
.I [Section]
.LP 
and continues until the next section.  Entries in sections are specified in key\-value pairs, in the form:
.LP 
.I entry=value
.LP 
Neither
.I entry
nor
.I value
should be enclosed in double quotes.
.SH "SUPPORTED SECTIONS AND ENTRIES"
.LP 
Additional rcd clients or Red Carpet Enterprise modules can add their own sections and entry/value pairs. The basic list of sections and entries is as follows:
.LP 
\fB[Network]\fR

.TP 
This section contains settings for rcd's network options, including what server to connect to, what proxy to use, and how many concurrent downloads are permitted.

.TP 
\fBhost=<url>\fR
This key specifies the server that rcd should connect to.  This is a URL.  By default rcd contacts \fIhttp://red\-carpet.ximian.com.\fR This key can be set with "rc set" or other rcd client settings tools.

.TP 
\fBenable\-premium=[true | false]\fR
This key specifies whether the server is an enhanced server.  Set this to true when connecting to a Red Carpet Express or Red Carpet Corporate Connect server.  This defaults to false.  This key can be set through rcd's preferences mechanism.

.TP 
\fBorg\-id=<organization id>\fR
When using an enhanced server, set this to the organization id so that the daemon can register the machine with the server.  This is unset and ignored by default; this key has no effect if \fBenable\-premium\fR is not true.

.TP 
\fBproxy=<url>\fR
The URL for a proxy.  This should always begin with the protocol https://, http://, socks4://, or socks5://, and end with a colon and port number. For example, if you're running squid on your local machine, you'll want to set this to http://localhost:3128.  This is unset and ignored by default. Note that rc set proxy\-url is used to set this value, but that the value itself is "proxy" rather than "proxy\-url."

.TP 
\fBproxy\-user=<username>\fR
For proxies requiring authentication, this is the username used. This is unset and ignored by default; this key has no effect if \fBproxy\fR is not set.  This key can be set with "rc set" or other rcd client settings tools.

.TP 
\fBproxy\-password=<password>\fR
For proxies requiring authentication, this is the password used. This is unset and ignored by default; this key has no effect if \fBproxy\fR is not set.  This key can be set with "rc set" or other rcd client settings tools.
.TP 

.TP 
\fBhttp10=[true | false]\fR
This option determines whether or not rcd uses HTTP 1.0 or 1.1 to connect to servers.  This setting may be helpful with some uncooperative proxies.  This defaults to false.  This key can be set with "rc set" or other rcd client settings tools.

.TP 
\fBmax\-downloads=<number>\fR
This option specifies how many concurrent package downloads rcd may start.  Users on slower connections will want to decrease this, whereas users with high bandwidth connections may want to increase this.  If set to 0, there is no limit and rcd will make as many connections as needed.  This defaults to 5.  This key can be set through rcd's preferences mechanism.

.LP 
\fB[Server]\fR
.TP 
This section contains settings related to rcd's server.
.br 
.TP 
\fBremote\-enabled=[true | false]\fR
Specifies whether rcd should listen to remote (TCP) connections.  This defaults to true.

.TP 
\fBport=<number>\fR
Specifies the port rcd should listen on for remote (TCP) connections. This defaults to 505.

.LP 
\fB[Cache]\fR
.TP 
This section contains settings related to rcd's download caches.

.TP 
\fBenabled=[true | false]\fR
Specifies whether rcd should cache downloaded data.  This defaults to true.  This key can be set with "rc set" or other rcd client settings tools.

.TP 
\fBdirectory=<directory>\fR
Specifies the parent directory where rcd should store cached downloaded data.  This defaults to /var/cache/redcarpet.  This key can be set through rcd's preferences mechanism.

.TP 
\fB[System]
This section contains settings related to rcd behavior.

.TP 
\fBcache\-age\-in\-days=<number>\fR
Specifies the number of days a package may be in the cache before it is removed.  This defaults to 30.  It has no effect if \fBcache\-cleanup\fR is not set.  This can be set with "rc set" or other rcd client settings tools.


.TP 
\fBcache\-cleanup=[true | false]\fR
Specifies whether the package cache should be cleaned up.  If this is off and caching is enabled, packages will accumulate in the cache directory until it is cleared manually.  This defaults to true.  This can be set through rcd's preferences mechanism. 

.TP 
\fBcache\-size\-in\-mb=<number>\fR
Specifies the total size in megabytes that the package cache may be before it is cleaned up.  This defaults to 300.  It has no effect if \fBcache\-cleanup\fR is not set.  

.TP 
\fBdebug\-level=<number>\fR
The level at which to log to standard error.  This can range from 0 to 6, where 6 is extremely verbose.  This setting defaults to 4 and can be set through rcd's preferences mechanism.

.TP 
\fBheartbeat=<number>\fR
Specifies the interval at which rcd downloads new channel and package metadata.  This defaults to 21600 (6 hours) and can be set through rcd's preferences mechanism.


.TP 
\fBrepackage=[true | false]\fR
Specifies whether to turn repackage and store the currently installed version of software as a backup, so that the "rc rollback" software reversion command can work (see rc(1) for more information). This option will cause a noticeable slowdown in upgrade and removal transactions, use a significant amount of disk space, and only works for RPM versions 4.0.4 and greater.

.TP 
\fBrequire\-signatures=[true | false]\fR
Specifies whether packages being installed must pass a GPG signature
check.  Packages which are inconclusive for whatever reason (gpg not
installed, public key unavailable, etc.) are not installed.
.I Note that rcd will never install packages in which a gpg signature
explicitly fails.
This defaults to false.  This key can be set through rcd's preferences
mechanism.

.TP 
\fBsyslog\-level=<number>
The level at which to log to syslog.  This can range from 0 to 6,
where 6 is extremely verbose.  This defaults to 4.  This can be set
through rcd's preferences mechanism.


.SH "AUTHORS"
.LP 
Copyright Ximian, Inc. 2002
http://www.ximian.com

.SH "SEE ALSO"
.LP 
rcd(8), rc(1), rcman(1), rcreports(1), rce\-dump, rce\-restore, rce\-getchannels(1), rcmirror(1)

.LP 
The graphical Red Carpet client, red\-carpet, has a manual accessible through the GNOME help system; select items from the Help menu within the application to read it.  Visit http://ximian.com for more information about rcd and the full family of Ximian Red Carpet products and servies, as well as Evolution and other software from Ximian.
To report problems with this software or its documentation, visit http://bugzilla.ximian.com

