.\" To report problems with this software, visit http://bugzilla.ximian.com
.TH "rcd" "8" "1.0" "Ximian, Inc. 2002" "Software management daemon"
.SH "NAME"
.LP 
rcd \- The backend daemon for rug, the command\-line version of the Ximian Red Carpet software management tool.
.SH "SYNTAX"
.LP 
/etc/init.d/rcd [\fIstart|stop|restart\fR] \fI<options>\fR
.br 
rcd \fI<options>\fR
.SH "DESCRIPTION"
.LP 
This daemon performs the Red Carpet software management functions that are asked of it by the rug software management tool, including the updating, installation, and removal of software, in addition to basic queries of the system's package management database. In general, you will not need to interact directly with rcd.
.LP 
The daemon is kept apart from the control application so that the control application can be used to administer remote systems. See the rug man page for more information about this process.
.SH "OPTIONS"
.LP 
\fBUSAGE OPTIONS:\fR
.TP 
\fB\-f, \-\-config=\fR[filename]
Choose an alternate configuration file. Normally the daemon uses rcd.conf; see the man page for rcd.conf(8) for details of the configuration file format.
.TP 
\fB\-\-allow\-non\-root\fR
Allows rcd to be run as a non\-root user.  This is likely to cause errors if rug attempts to do anything other than query the package database.
.TP 
\fB\-d, \-\-debug=\fR[INT]
Turn on debugging mode. You may specify a number between 1 and 6 to determine how much debugging output you woul d like. 1 displays only the highest priority messages, and 6 displays all messages. Choosing zero causes the debugging mode to display no messages at all. The default is 4.
.TP 
\fB\-n, \-\-non\-daemon\fR
Do not run the daemon in the background.
.TP 
\fB\-\-no\-network\fR
Do not connect to the network or download any data from the server until the heartbeat interval or the command "rug refresh" is run.
.TP 
\fB\-o, \-\-download\-distro\fR
Download new distribution information from the server right away.
.TP 
\fB\-i, \-\-ipaddress=\fR[IP address]
Bind the remote server only to the specified IP address. This is for systems which host more than one IP address, and means that the server will be available only on the IP address you choose, rather than on all addresses leading to the system.
.TP 
\fB\-p, \-\-port=\fR[portnumber]
Listen for remote connections on the specified port. 	
.TP 
\fB\-m, \-\-no\-modules\fR
Do not load any optional modules.
.TP 
\fB\-r, \-\-no\-remote\fR
Do not listen for remote connections. This means that the daemon can only be controlled from the local system.
.TP 
\fB\-s, \-\-syslog=\fR[INT]
Specify the verbosity of logging information from 0 (none) to 6 (very). The default is 4.
.TP 
\fB\-\-undump=\fR[filename]
Initialize daemon from a dump file; dump files can be gotten from cur_to_xml or from libredcarpet examples.
.BR 
.LP 
\fBHELP OPTIONS\fR
.TP 
\fB\-\-help, \-?\fR
Output help information and exit.
.TP 
\fB\-\-usage\fR
Output usage message and then exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "FILES"
.TP 
\fI/etc/ximian/rcd.conf\fR
Configuration file.  Options such as proxy and cache settings can be adjusted through this file directly or with the \fBrug set\fR command. This file is documented in the man page rcd.conf(5). Note that the remote server is not set in this file.

.TP 
\fI/etc/ximian/rc\-passwd\fR
Password file.  This file lists users, passwords for remote access,
and privileges for various actions.

.TP 
\fI/etc/init.d/rcd\fR 
Initialization script. It is recommended that you use this script to start and stop rcd, rather than running it directly.

.TP 
\fI/var/log/rcd/rcd\-messages\fR 
Log file.

.TP 
\fI/var/log/rcd/rcd\-package\-history\fR
Transaction history.  This lists a record of all package
installations, removals, and upgrades.

.TP 
\fI/var/lib/rcd\fP
Cached channel and package data.

.TP 
\fI/var/lib/rcd/services.xml\fR
List of servers from which rcd will download software and package information.

.TP 
\fI/var/lib/redcarpet/subscriptions.xml\fP
Channel subscription information.

.TP 
\fI/var/cache/redcarpet\fP
Cached downloaded data.  Includes channel icons, package files, and
channel and package metadata.

.SH "EXAMPLES"
This program normally runs as root.

.TP 
To run this program the standard way type:
\fB/etc/init.d/rcd start\fR
.TP 
Alternately, run the program directly:
\fB/usr/sbin/rcd\fR
.SH "AUTHORS"
.LP 
Copyright Ximian, Inc. 2002\-2003
http://www.ximian.com
.SH "SEE ALSO"
.LP 
rcd.conf(5), rcserver.conf(5), rug(1), rcman(1), rcreports(1), rce\-dump, rce\-init, rce\-restore, rcmirror(1) rcd\-mp\-server(8), rcd\-mp\-middleman(8), rcd\-mp\-client(8)
.LP 
The graphical Red Carpet client, red\-carpet, has a manual accessible through the GNOME help system; select items from the Help menu within the application to read it. Visit http://ximian.com for more information about rcd and the full family of Ximian Red Carpet products and servies, as well as Evolution and other software from Ximian.
To report problems with this software or its documentation, visit http://bugzilla.ximian.com
