.\" To report problems with this software, visit http://bugzilla.ximian.com
.TH "rcd" "8" "1.0" "Ximian, Inc. 2002" "Software management daemon"
.SH "NAME"
.LP 
rcd \- The backend daemon for rc, the command\-line version of the Ximian Red Carpet software management tool.
.SH "SYNTAX"
.LP 
/etc/init.d/rcd [\fIstart|stop|restart\fR] \fI<options>\fR
.br 
rcd \fI<options>\fR
.SH "DESCRIPTION"
.LP 
This daemon performs the Red Carpet software management functions that are asked of it by the rc software management tool, including the updating, installation, and removal of software, in addition to basic queries of the system's package management database. In general, you will not need to interact directly with rcd.
.LP 
The daemon is kept apart from the control application so that the control application can be used to administer remote systems. See the rc man page for more information about this process.
.SH "OPTIONS"
.LP 
\fBUSAGE OPTIONS:\fR
.TP 
\fB\-allow\-non\-root\fR <\fIdirectory\fP>
Allows rcd to be run by non\-root users.  This is likely to cause errors when rc users attempt to do anything other than query the package database.
.TP 
\fB\-d, \-\-debug=\fI<INT>\fR
Turn on debugging mode. You may specify a number between 1 and 6 to determine how much debugging output you woul d like. 1 displays only the highest priority messages, and 6 displays all messages. Choosing zero causes the debugging mode to display no messages at all.
.TP 
\fB\-n, \-\-nodaemon\fR
Do not run the daemon in the background.
.TP 
\fB\-\-late\-background\fR
Keep the daemon as a foreground process until it is ready to accept connections.
.TP 
\fB\-r, \-\-no\-remote\fR
Do not listen for remote connections. This means that the daemon can only be controlled from the local system.
.TP 
\fB\-s, \-\-syslog=\fI<INT>\fR
Specify the verbosity of logging information.
.TP 
\fB\-\-undump=\fI<filename>\fR
Initialize daemon from a dump file; dump files can be gotten from cur_to_xml or from libredcarpet examples).
.BR 
.LP 
\fBHELP OPTIONS\fR
.TP 
\fB\-\-help, \-?\fR
Output help information and exit.
.TP 
\fB\-\-usage\fR
Output usage message and then exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "FILES"
.TP 
\fI/etc/ximian/rcd.conf\fP
Configuration file.  Options such as the server to contact, proxy
configuration, and other settings can be set through this file.

.TP 
\fI/etc/ximian/rc\-passwd\fP
Password file.  This file lists users, passwords for remote access,
and privileges for various actions.

.TP 
\fI/etc/init.d/rcd\fP 
Initialization script. It is recommended that you use this script to start and stop rcd, rather than running it directly.

.TP 
\fI/var/log/rcd/rcd\-messages\fP 
Log file.

.TP 
\fI/var/log/rcd/rcd\-package\-history\fP
Transaction history.  This lists a record of all package
installations, removals, and upgrades.

.TP 
\fI/var/lib/rcd\fP
Cached channel and package data.

.TP 
\fI/var/lib/redcarpet/subscriptions.xml\fP
Channel subscription information.

.TP 
\fI/var/cache/redcarpet\fP
Cached downloaded data.  Includes channel icons, package files, and
channel and package metadata.

.SH "EXAMPLES"
This program normally runs as root.

.TP 
To run this program the standard way type:
\fB/etc/init.d/rcd start\fR
.TP 
Alternately, run the program directly:
\fB/usr/sbin/rcd\fR
.SH "AUTHORS"
.LP 
Copyright Ximian, Inc. 2002
http://www.ximian.com
.SH "SEE ALSO"
.LP 
rcd.conf(5), rc(1), rcman(1), rcreports(1), rc\-dump, rc\-restore, rce\-getchannels(1), red\-carpet(GNOME application),
.LP 

The graphical Red Carpet client, red\-carpet, has a manual accessible through the GNOME help system; select items from the Help menu within the application to read it. Visit http://ximian.com for more information about rcd and the full family of Ximian Red Carpet products and servies, as well as Evolution and other software from Ximian.
To report problems with this software or its documentation, visit http://bugzilla.ximian.com
